### ISSUE TITLE
change links name

### ISSUE THREAD

**Issue by saankalpaa** [Biijeta/Project-1#1]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/61270616/179446515-64928139-70a1-42fb-a23e-c799faa3cd9e.png">

I can see that you have used /project1.html, /project2.html, and so on for links.
Here, you can do /home, /about, /contact 

You can refer to [https://testbook.com/blog/how-to-link-two-html-pages-together/] for reference.

**Comment by Biijeta** [comment]
Changed the names to /home, /photos, and /contact to better reflect the content of the html files.
