### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by saankalpaa** [Biijeta/Project-1#2]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/61270616/179446867-353baeb4-67a9-4d23-bd38-4fd65cc51542.png">

Here, you can set a background as an image (the theme can be pride or anything you like ) 
and make sure the background image covers the whole screen below navbar

**Comment by Biijeta** [comment]
Added photo to the folder so that now it shows in the homepage.
