### ISSUE TITLE
photos page

### ISSUE THREAD

**Issue by saankalpaa** [Biijeta/Project-1#4]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61270616/179447144-332c174c-da47-467a-9a36-524f5075c78e.png">

Instead of writing the name of the photos, it would be great if you could make a gallery of photos here.

**Comment by saankalpaa** [comment]
also make sure that the background covers the whole screen

**Comment by Biijeta** [comment]
I fixed the code and added photos to the folder so now they display in the webpage.
